Fix out-of-bounds array access in preposition vocabulary
richelbilderbeek/Zork pull request #2
Opened 2023-01-13 21:47 UTC by fuulish

Fixes the segmentation fault documented in the README.md.

2023-01-18 08:21 UTC, richelbilderbeek requested changes
Hi @fuulish, thanks for the PR! I will happily accept after knowing what it is about. In fact, I will accept in a month in any case, as I trust your judgement.

Yet, I'd enjoy to know the 'why' behind this commit. The goal of this repo is to use the code I found somewhere and get it to work with `qmake`. It does not intend to fix that code at all. I do enjoy this fix (I trust your judgement!), so I (or you) will happily add to the README what changes are done and why. Would you be up for that?

2023-02-12 20:59 UTC, fuulish commented
Sure thing. The commit fixes the segmentation fault that you quote at the bottom of your readme:

> When you have built Zork using build.sh and started the game with ./Zork most commands terminate the program with a segmentation fault.

The `pvoc` array only has 45 members, yet, `prplnt` was set to 48 and used as boundary for the loop around line 126 of file NP1.C:

```
L200:
	i__2 = prplnt;
	for (j = 1; j <= i__2; j += 3) {
/* 						!LOOK FOR PREPOSITION. */
	    if (lbuf1 == prpvoc_1.pvoc[j - 1] && lbuf2 == prpvoc_1.pvoc[j]) {
		goto L4000;
	    }
```

This results in undefined behavior and thus (depending on, e.g., compiler) the aforementioned segmentation fault.

2023-02-13 07:30 UTC, richelbilderbeek commented
This is a great explanation, thanks so much for the effort!

2023-02-13 07:30 UTC, richelbilderbeek approved these changes

2023-02-13 07:30 UTC, merged